import os
from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

app = FastAPI(
    title="R Markdown static app",
    description="Serves static content generated by R Markdown",
    version="1.0.0",
)

api_app = FastAPI()


@api_app.get("/v1/healthcheck")
async def healthcheck():
    """Return the API status."""
    return {"status": "ok"}


app.mount("/api", api_app)

# Static content: from STATIC_CONTENT_PATH (e.g. volume) or default "static"
static_dir = os.getenv("STATIC_CONTENT_PATH", "static")
static_path = Path(static_dir).resolve()

if not static_path.exists():
    if os.getenv("STATIC_CONTENT_PATH"):
        raise RuntimeError(
            f"Static content directory does not exist: {static_path}. "
            "Render the R Markdown report to this path first (e.g. set STATIC_OUTPUT_DIR and run render_report.R)."
        )
    static_path.mkdir(parents=True, exist_ok=True)

if not static_path.is_dir():
    raise RuntimeError(f"STATIC_CONTENT_PATH is not a directory: {static_path}")

ui_app = StaticFiles(directory=str(static_path), html=True)
app.mount("/", ui_app)
